$pagePath = Join-Path $PSScriptRoot "..\showcase\app\zh\page.tsx"
$cssPath = Join-Path $PSScriptRoot "..\showcase\app\zh\page.module.css"
$dockerfilePath = Join-Path $PSScriptRoot "..\deploy\showcase.Dockerfile"
$page = [System.IO.File]::ReadAllText($pagePath)
$css = [System.IO.File]::ReadAllText($cssPath)
$dockerfile = [System.IO.File]::ReadAllText($dockerfilePath)

function Replace-Once([string]$source, [string]$old, [string]$new, [string]$name) {
  $first = $source.IndexOf($old, [System.StringComparison]::Ordinal)
  if ($first -lt 0) { throw "$name was not found." }
  if ($source.IndexOf($old, $first + $old.Length, [System.StringComparison]::Ordinal) -ge 0) { throw "$name was found more than once." }
  return $source.Replace($old, $new)
}

$oldState = @'
  const [tick, setTick] = useState(0);
  const activeStage = tick % copy.stages.length;
  const cycle = Math.floor(tick / copy.stages.length) + 1;
'@.Trim()
$newState = @'
  const [tick, setTick] = useState(0);
  const demoLength = copy.stages.length + 1;
  const phase = tick % demoLength;
  const completed = phase === copy.stages.length;
  const activeStage = completed ? copy.stages.length - 1 : phase;
  const cycle = Math.floor(tick / demoLength) + 1;
'@.Trim()
$page = Replace-Once $page $oldState $newState "Auto-plan state block"

$page = Replace-Once $page '<div className={styles.demoTop}><span><i className={styles.pulse} /> AUTOPLAN-AGENT-CORE</span><small>{String(cycle).padStart(2, "0")} / AUTO</small></div>' '<div className={styles.demoTop}><span><i className={styles.pulse} /> {completed ? "TASK COMPLETED" : "AUTOPLAN-AGENT-CORE"}</span><small>{String(cycle).padStart(2, "0")} / AUTO</small></div>' "Demo status heading"
$page = Replace-Once $page '<div className={styles.liveDetail}>{stageDetails[activeStage]}</div>' '<div className={styles.liveDetail}>{completed ? "\u5168\u90e8\u5b50\u4efb\u52a1\u5df2\u5b8c\u6210\uff0c\u5df2\u4ea4\u4ed8\u6700\u7ec8\u4ea7\u7269\u3002" : stageDetails[activeStage]}</div>' "Live detail"

$oldStepState = @'
          const complete = index < activeStage;
          const active = index === activeStage;
'@.Trim()
$newStepState = @'
          const complete = completed || index < activeStage;
          const active = !completed && index === activeStage;
'@.Trim()
$page = Replace-Once $page $oldStepState $newStepState "Step state mapping"

$oldOutput = @'
        <div className={`${styles.demoOutput} ${activeStage === copy.stages.length - 1 ? styles.outputActive : ""}`}>
          <img src="/crispix/tool-01.webp" alt="Jenda generated result" /><span><b>jenda_poster_final.png</b><small>{activeStage === copy.stages.length - 1 ? "Generating preview..." : "Waiting for final output"}</small><i /></span>
        </div>
'@.Trim()
$newOutput = @'
        <div className={`${styles.demoOutput} ${(activeStage === copy.stages.length - 1 || completed) ? styles.outputActive : ""}`}>
          <img src="/crispix/tool-01.webp" alt="Jenda generated result" /><span><strong>{completed ? "\u4efb\u52a1\u5b8c\u6210" : "OUTPUT PREVIEW"}</strong><b>{completed ? "output_poster_final.png" : "jenda_poster_final.png"}</b><small>{completed ? "Generated by Jenda Agent" : activeStage === copy.stages.length - 1 ? "Generating preview..." : "Waiting for final output"}</small><i /></span>
        </div>
'@.Trim()
$page = Replace-Once $page $oldOutput $newOutput "Output card"

$dockerNeedle = 'COPY --from=builder --chown=node:node /app/.next ./.next'
$dockerReplacement = @'
COPY --from=builder --chown=node:node /app/.next ./.next
# Next.js serves images and other static assets from public at runtime.
COPY --from=builder --chown=node:node /app/public ./public
'@.Trim()
$dockerfile = Replace-Once $dockerfile $dockerNeedle $dockerReplacement "Public asset Docker copy"

$css += @'

.demoOutput strong{display:block;margin-bottom:3px;color:#3a86ff;font-size:9px;font-weight:800;letter-spacing:.11em}.demoOutput.outputActive strong{color:#1764c7}.demoOutput.outputActive img{animation:resultReveal .5s ease both}@keyframes resultReveal{from{opacity:.55;transform:scale(.96)}to{opacity:1;transform:scale(1)}}
'@

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($pagePath, $page, $utf8)
[System.IO.File]::WriteAllText($cssPath, $css, $utf8)
[System.IO.File]::WriteAllText($dockerfilePath, $dockerfile, $utf8)
Write-Output "Applied Step 38 final output state and public asset image fix."
