$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$path = Join-Path $root "showcase\app\zh\page.tsx"
$source = @'
"use client";

import Link from "next/link";
import { Button } from "antd";
import { ArrowRightOutlined, CheckCircleFilled, PlayCircleOutlined } from "@ant-design/icons";
import { CrispixHeader } from "../../components/CrispixHeader";
import styles from "./page.module.css";

const copy = {
  newModel: "\u91cd\u78c5\u63a5\u5165",
  title: "\u81ea\u4e3b\u89c4\u5212\uff0c\u667a\u80fd\u521b\u4f5c",
  description: "\u4ee5 AI \u81ea\u4e3b\u89c4\u5212\u7684\u56fe\u50cf\u667a\u80fd\u4f53\u4e3a\u6838\u5fc3\uff0c\u7406\u89e3\u60a8\u7684\u9700\u6c42\uff0c\u81ea\u52a8\u62c6\u89e3\u5e76\u5b8c\u6210\u56fe\u50cf\u4efb\u52a1\u3002",
  demoPrompt: "\u8bf7\u5e2e\u6211\u8bbe\u8ba1\u4e00\u5f20\u79d1\u6280\u98ce\u683c\u7684\u53d1\u5e03\u4f1a\u6d77\u62a5",
  engines: "\u53cc\u6838\u5f15\u64ce",
  engineLead: "\u4ee5\u667a\u80fd\u4f53\u4e3a\u6838\u5fc3\uff0cAI \u529f\u80fd\u4e3a\u8f85\u52a9\uff0c\u8ba9\u590d\u6742\u7684\u56fe\u50cf\u9700\u6c42\u53d8\u5f97\u7b80\u5355\u3002",
  fromIdea: "\u4ece\u60f3\u6cd5\u5230\u6210\u679c",
  oneSentence: "\u53ea\u9700\u4e00\u53e5\u8bdd",
  toolbox: "AI \u5de5\u5177\u7bb1",
};

const tools = [
  ["tool-01.webp", "\u56fe\u50cf\u53d8\u6e05\u6670", "AI \u8d85\u5206\u8fa8\u7387\u6280\u672f\uff0c\u4e00\u952e\u63d0\u5347\u753b\u9762\u7ec6\u8282"],
  ["tool-02.jpeg", "\u56fe\u7247\u53d8\u624b\u529e", "\u98ce\u683c\u8fc1\u79fb\u6280\u672f\uff0c\u4fdd\u7559\u4eba\u7269\u7279\u5f81"],
  ["tool-03.png", "\u63d0\u53d6\u4ea7\u54c1\u767d\u5e95\u56fe", "\u667a\u80fd\u5206\u79bb\u4e3b\u4f53\u4e0e\u80cc\u666f"],
  ["tool-04.png", "\u98ce\u683c\u8f6c\u6362", "\u6cb9\u753b\u3001\u6c34\u5f69\u3001\u7d20\u63cf\u4e0e\u5361\u901a\u98ce\u683c"],
];

export default function ZhHomePage() {
  return (
    <main className={styles.page}>
      <CrispixHeader />
      <section className={styles.hero}>
        <div className={styles.heroCopy}>
          <span className={styles.kicker}>NEW &nbsp; GPT-IMAGE-2 {copy.newModel}</span>
          <p className={styles.eyebrow}>AUTOPLAN AGENT CORE</p>
          <h1>Crispix Agent</h1>
          <h2>{copy.title}</h2>
          <p>{copy.description}</p>
          <div className={styles.heroActions}>
            <Button type="primary" size="large" href="/zh/agent">\u7acb\u5373\u4f53\u9a8c <ArrowRightOutlined /></Button>
            <Button size="large" icon={<PlayCircleOutlined />}>\u89c2\u770b\u6f14\u793a</Button>
          </div>
        </div>
        <div className={styles.agentDemo}>
          <div className={styles.demoTop}><span>O&nbsp; AGENT RUNNING</span><small>01 / 04</small></div>
          <div className={styles.quote}>{copy.demoPrompt}</div>
          {["\u9700\u6c42\u7406\u89e3", "\u7d20\u6750\u641c\u7d22", "\u56fe\u50cf\u751f\u6210", "\u540e\u671f\u4f18\u5316"].map((item, index) => (
            <div className={styles.demoStep} key={item}>
              <span>{index < 2 ? <CheckCircleFilled /> : <i />}</span><b>{item}</b><small>{index < 2 ? "Complete" : "Waiting"}</small>
            </div>
          ))}
          <div className={styles.demoOutput}><img src="/crispix/tool-01.webp" alt="generated result" /><span><b>output_poster_final.png</b><small>Generated by Crispix Agent</small></span></div>
        </div>
      </section>
      <section className={styles.section}>
        <p className={styles.eyebrow}>DUAL ENGINE</p><h2>{copy.engines}</h2><p className={styles.lead}>{copy.engineLead}</p>
        <div className={styles.engineGrid}>
          <article><span>01</span><h3>ReAct \u6a21\u5f0f</h3><p>\u9002\u5408\u5feb\u901f\u95ee\u7b54\u3001\u56fe\u50cf OCR \u4e0e\u5355\u6b65\u5de5\u5177\u8c03\u7528\u3002</p><b>\u5feb\u901f &middot; \u4f4e\u5ef6\u8fdf</b></article>
          <article className={styles.featured}><span>02</span><h3>Plan \u6a21\u5f0f</h3><p>\u81ea\u52a8\u62c6\u89e3\u590d\u6742\u76ee\u6807\uff0c\u591a\u667a\u80fd\u4f53\u5e76\u53d1\u6267\u884c\u5e76\u81ea\u6211\u53cd\u601d\u3002</p><b>\u6df1\u5ea6\u89c4\u5212 &middot; \u52a8\u6001\u95ed\u73af</b></article>
        </div>
      </section>
      <section className={styles.showcase}>
        <div><p className={styles.eyebrow}>FROM IDEA TO DELIVERY</p><h2>{copy.fromIdea}<br /><em>{copy.oneSentence}</em></h2><p>\u667a\u80fd\u4f53\u4f1a\u5206\u6790\u4f60\u7684\u76ee\u6807\uff0c\u9009\u62e9\u5408\u9002\u7684\u5de5\u5177\uff0c\u4ea4\u4ed8\u53ef\u76f4\u63a5\u4f7f\u7528\u7684\u6210\u54c1\u3002</p><Link href="/zh/agent">\u4e86\u89e3\u89c4\u5212\u7b97\u6cd5 <ArrowRightOutlined /></Link></div>
        <div className={styles.poster}><img src="/crispix/tool-02.jpeg" alt="summer drink poster" /><span>Summer Vibes Collection</span></div>
      </section>
      <section className={styles.tools}><p className={styles.eyebrow}>CRISPIX TOOL</p><h2>{copy.toolbox}</h2><div className={styles.toolGrid}>{tools.map(([image, title, desc]) => <Link href="/zh/tool" key={title}><img src={`/crispix/${image}`} alt={title} /><div><h3>{title}</h3><p>{desc}</p><span>\u70b9\u51fb\u8bd5\u7528 <ArrowRightOutlined /></span></div></Link>)}</div><Link href="/zh/tool" className={styles.more}>\u8fdb\u5165\u5de5\u5177\u7bb1 <ArrowRightOutlined /></Link></section>
      <footer><b>Crispix AI</b><span>2025 Created for JendaAgent</span></footer>
    </main>
  );
}
'@
[System.IO.File]::WriteAllText($path, $source, [System.Text.UTF8Encoding]::new($false))
Write-Output "Fixed Step 34 home JSX."
